### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by agate-pris** [agate-pris/noer#1]
- [x] 厳密な数値演算を行うクラス `exact_number` を追加する
- [ ] 角度系
  - [ ] 絶対角度クラスを `angle` から `angle::absolute` に変更
  - [ ] 相対角度クラス `angle::relative` を追加
  - [ ] 各種角度クラスを実行時管理するための多態クラス群とインタフェースを追加
- [ ] 当たり判定 `collision_detecsion` と `intersects`
- [ ] MT MTd MD MDd を選べるように変更
