### ISSUE TITLE
todo fraction

### ISSUE THREAD

**Issue by agate-pris** [agate-pris/noer#3]
- [ ] そもそも Boost.Rational で十分かもしれないので調査
- [ ] fraction_traits の特殊化を追加
- [ ] フリー関数 numerator を追加
- [ ] フリー関数 denominator を追加
- [ ] operator *= を追加
- [ ] operator /= を追加
- [ ] operator \* を追加
- [ ] operator / を追加
