### ISSUE TITLE
todo exact_number

### ISSUE THREAD

**Issue by agate-pris** [agate-pris/noer#4]
- [x] get 関数を private に変更
- [x] operator Target() を削除
- [x] ADL Firewall 内に convert_to 関数を作成
- [x] ADL Firewall 内に get 関数を作成

**Comment by agate-pris** [comment]
get 関数は非メンバ関数に変更。
